-- =====================================================================
--  Complément séance 2 — SQL avancé avec PostgreSQL
--  À exécuter sur la base cours_sql, APRÈS demo.sql.
--  Ajoute un catalogue de jeux vidéo (JSONB) et leurs ventes.
--  Script ré-exécutable : il supprime puis recrée ses tables.
--  Données simplifiées : plateformes non exhaustives, ventes fictives.
-- =====================================================================

DROP TABLE IF EXISTS ventes, jeux CASCADE;

CREATE TABLE jeux (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre    VARCHAR(80) NOT NULL UNIQUE,
    details  JSONB       NOT NULL             -- fiche du jeu, structure variable
);

INSERT INTO jeux (titre, details) VALUES
 ('Rocket League',       '{"editeur": "Psyonix", "genres": ["sport", "course"], "plateformes": ["PC", "PS5", "Switch"], "pegi": 3, "multijoueur": true, "prix": 19.99}'),
 ('EA Sports FC 25',     '{"editeur": "EA Sports", "genres": ["sport"], "plateformes": ["PC", "PS5", "Xbox"], "pegi": 3, "multijoueur": true, "prix": 69.99}'),
 ('Mario Kart 8 Deluxe', '{"editeur": "Nintendo", "genres": ["course"], "plateformes": ["Switch"], "pegi": 3, "multijoueur": true, "prix": 59.99}'),
 ('Elden Ring',          '{"editeur": "Bandai Namco", "genres": ["action", "rpg"], "plateformes": ["PC", "PS5", "Xbox"], "pegi": 16, "multijoueur": false, "prix": 59.99, "dlc": {"nom": "Shadow of the Erdtree", "prix": 39.99}}'),
 ('Hades',               '{"editeur": "Supergiant Games", "genres": ["action", "roguelike"], "plateformes": ["PC", "Switch"], "pegi": 12, "multijoueur": false, "prix": 24.99}'),
 ('Tetris Effect',       '{"editeur": "Enhance", "genres": ["puzzle"], "plateformes": ["PC", "PS5", "Switch"], "pegi": 3, "multijoueur": true, "prix": 39.99}'),
 ('Stardew Valley',      '{"editeur": "ConcernedApe", "genres": ["simulation", "rpg"], "plateformes": ["PC", "Switch"], "pegi": 7, "multijoueur": true, "prix": 13.99}'),
 ('Gran Turismo 7',      '{"editeur": "Sony Interactive Entertainment", "genres": ["course", "simulation"], "plateformes": ["PS5"], "pegi": 3, "multijoueur": true, "prix": 79.99}');

CREATE TABLE ventes (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jeu_id         INTEGER      NOT NULL REFERENCES jeux(id),
    plateforme     VARCHAR(10)  NOT NULL,
    mois           DATE         NOT NULL,            -- 1er jour du mois
    quantite       INTEGER      NOT NULL CHECK (quantite >= 0),
    prix_unitaire  NUMERIC(6,2) NOT NULL CHECK (prix_unitaire >= 0)
);

-- Une ligne par jeu, par plateforme et par mois (janvier à juin 2026)
INSERT INTO ventes (jeu_id, plateforme, mois, quantite, prix_unitaire)
SELECT j.id, p.plateforme, m.mois::DATE,
       100 + (('x' || substr(md5(j.id || p.plateforme || to_char(m.mois, 'YYYY-MM')), 1, 6))::bit(24)::int % 400),
       (j.details ->> 'prix')::NUMERIC
FROM jeux j
CROSS JOIN LATERAL jsonb_array_elements_text(j.details -> 'plateformes') AS p(plateforme)
CROSS JOIN generate_series('2026-01-01'::DATE, '2026-06-01'::DATE, INTERVAL '1 month') AS m(mois)
ORDER BY j.id, p.plateforme, m.mois;

-- ---------- Contrôle ----------
SELECT 'jeux' AS table_name, COUNT(*) AS lignes FROM jeux
UNION ALL SELECT 'ventes', COUNT(*) FROM ventes;
