-- =====================================================================
--  Jeu de données de démonstration — SQL avancé avec PostgreSQL
--  Domaines : sport (championnat), musique (genres, streams), jeux vidéo
--  Script ré-exécutable : il supprime puis recrée toutes les tables.
-- =====================================================================

-- (tournois et inscriptions sont créées pendant les exercices N2)
DROP TABLE IF EXISTS inscriptions, tournois, joueurs, matchs, equipes, genres, parties, streams CASCADE;

-- ---------- SPORT : un mini-championnat de 6 équipes ----------
CREATE TABLE equipes (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom   VARCHAR(50) NOT NULL UNIQUE,
    ville VARCHAR(50) NOT NULL
);

CREATE TABLE joueurs (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom       VARCHAR(80) NOT NULL,
    equipe_id INTEGER REFERENCES equipes(id),      -- NULL = joueur sans club
    poste     VARCHAR(20) NOT NULL,
    buts      INTEGER NOT NULL DEFAULT 0 CHECK (buts >= 0)
);

CREATE TABLE matchs (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    journee        INTEGER NOT NULL,
    equipe_dom_id  INTEGER NOT NULL REFERENCES equipes(id),
    equipe_ext_id  INTEGER NOT NULL REFERENCES equipes(id),
    buts_dom       INTEGER NOT NULL CHECK (buts_dom >= 0),
    buts_ext       INTEGER NOT NULL CHECK (buts_ext >= 0)
);

INSERT INTO equipes (nom, ville) VALUES
  ('PSG', 'Paris'), ('OM', 'Marseille'), ('OL', 'Lyon'),
  ('LOSC', 'Lille'), ('Stade Rennais', 'Rennes'), ('RC Lens', 'Lens');

INSERT INTO joueurs (nom, equipe_id, poste, buts) VALUES
  ('Yanis Belkacem', 1, 'attaquant', 7),
  ('Hugo Martin',    1, 'milieu',    2),
  ('Enzo Rossi',     2, 'attaquant', 5),
  ('Adam Diallo',    2, 'défenseur', 0),
  ('Lucas Moreau',   3, 'attaquant', 4),
  ('Noah Petit',     4, 'milieu',    1),
  ('Rayan Ndiaye',   5, 'attaquant', 2),
  ('Ilyes Haddad',   6, 'attaquant', 6),
  ('Théo Garnier',   6, 'défenseur', 1),
  ('Sami Koné',   NULL, 'attaquant', 0);

INSERT INTO matchs (journee, equipe_dom_id, equipe_ext_id, buts_dom, buts_ext) VALUES
  (1, 1, 2, 3, 1), (1, 3, 4, 2, 2), (1, 5, 6, 0, 1),
  (2, 1, 3, 1, 1), (2, 2, 5, 2, 0), (2, 4, 6, 1, 3),
  (3, 1, 4, 2, 0), (3, 2, 6, 1, 1), (3, 3, 5, 3, 1),
  (4, 1, 5, 4, 2), (4, 2, 4, 2, 1), (4, 3, 6, 0, 2),
  (5, 1, 6, 1, 2), (5, 2, 3, 2, 2), (5, 4, 5, 1, 1);

-- ---------- MUSIQUE : arbre des genres + streams mensuels ----------
CREATE TABLE genres (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom       VARCHAR(50) NOT NULL UNIQUE,
    parent_id INTEGER REFERENCES genres(id)         -- NULL = genre racine
);

INSERT INTO genres (nom, parent_id) VALUES
  ('Rock', NULL),        -- 1
  ('Metal', 1),          -- 2
  ('Heavy metal', 2),    -- 3
  ('Thrash metal', 2),   -- 4
  ('Punk', 1),           -- 5
  ('Électro', NULL),     -- 6
  ('House', 6),          -- 7
  ('Deep house', 7),     -- 8
  ('Techno', 6),         -- 9
  ('Hip-hop', NULL),     -- 10
  ('Trap', 10),          -- 11
  ('Drill', 11);         -- 12

CREATE TABLE streams (
    artiste  VARCHAR(50) NOT NULL,
    mois     DATE        NOT NULL,          -- 1er jour du mois
    ecoutes  INTEGER     NOT NULL CHECK (ecoutes >= 0),
    PRIMARY KEY (artiste, mois)
);

INSERT INTO streams (artiste, mois, ecoutes) VALUES
  ('Nova',  '2026-01-01', 12000), ('Nova',  '2026-02-01', 15000),
  ('Nova',  '2026-03-01', 14000), ('Nova',  '2026-04-01', 21000),
  ('Nova',  '2026-05-01', 30000), ('Nova',  '2026-06-01', 28000),
  ('Kairo', '2026-01-01',  8000), ('Kairo', '2026-02-01',  9000),
  ('Kairo', '2026-03-01', 13000), ('Kairo', '2026-04-01', 12500),
  ('Kairo', '2026-05-01', 12500), ('Kairo', '2026-06-01', 19000);

-- ---------- JEUX VIDÉO : scores de parties ----------
CREATE TABLE parties (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pseudo      VARCHAR(30) NOT NULL,
    jeu         VARCHAR(30) NOT NULL,
    score       INTEGER     NOT NULL CHECK (score >= 0),
    date_partie DATE        NOT NULL
);

INSERT INTO parties (pseudo, jeu, score, date_partie) VALUES
  ('Zed',   'Tetris',  12000, '2026-09-01'),
  ('Lyna',  'Tetris',  15000, '2026-09-02'),
  ('Mo',    'Tetris',  15000, '2026-09-03'),
  ('Kenji', 'Tetris',   9000, '2026-09-03'),
  ('Sara',  'Tetris',  11000, '2026-09-04'),
  ('Zed',   'Pac-Man',  8000, '2026-09-01'),
  ('Lyna',  'Pac-Man',  5000, '2026-09-02'),
  ('Mo',    'Pac-Man',  8000, '2026-09-05'),
  ('Kenji', 'Pac-Man',  9500, '2026-09-06'),
  ('Sara',  'Pac-Man',  7000, '2026-09-06'),
  ('Zed',   'Tetris',  13500, '2026-09-08'),
  ('Lyna',  'Pac-Man',  6500, '2026-09-09');

-- ---------- Contrôle : chaque table doit afficher le bon nombre de lignes ----------
SELECT 'equipes' AS table_name, COUNT(*) AS lignes FROM equipes
UNION ALL SELECT 'joueurs', COUNT(*) FROM joueurs
UNION ALL SELECT 'matchs',  COUNT(*) FROM matchs
UNION ALL SELECT 'genres',  COUNT(*) FROM genres
UNION ALL SELECT 'streams', COUNT(*) FROM streams
UNION ALL SELECT 'parties', COUNT(*) FROM parties;
